
# Run
# ./gradlew build
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.jvm -t quarkus/petstore .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/petstore

FROM openjdk:11-jre-slim

COPY build/petstore-runner.jar /petstore.jar

CMD ["java", "-jar", "/petstore.jar"]
